name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: us-east-1
      - name: Build, tag, and push image to ECR
        env:
          ECR_REGISTRY: 847795003432.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: vijivati-web
          IMAGE_TAG: latest
        run: |
          docker build -t vijivati-web . 
          docker push 847795003432.dkr.ecr.us-east-1.amazonaws.com/vijivati-web:latest
