name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry: 847795003432.dkr.ecr.us-east-1.amazonaws.com
          aws-access-key-id: AKIA4KZEFEAUAV34OMFO
          aws-secret-access-key: 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

      - name: Build, tag, and push Docker image to Amazon ECR
        env:
          REGISTRY: 847795003432.dkr.ecr.us-east-1.amazonaws.com
          REPOSITORY: vijivati-web
          IMAGE_TAG: latest
        run: |
          docker build -t vijivati-web .
          docker tag vijivati-web:latest 847795003432.dkr.ecr.us-east-1.amazonaws.com/vijivati-web:latest
          docker push 847795003432.dkr.ecr.us-east-1.amazonaws.com/vijivati-web:latest
